version: "3"
services:
  ci_cd_manager:
    image: 5gasp:ci_cd_manager
    depends_on:
      - "db"
    ports:
      - 8000:80
    volumes:
      - ./conf_files/config.ini:/app/config.ini
      - ./conf_files/testbeds_information.yaml:/app/static/testbeds_information.yaml

  results_repository:
    image: bogem/ftp
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      - FTP_USER=ftp-user
      - FTP_PASS=kXCPs96SfPPFSyLB
      - PASV_ADDRESS=10.0.12.86
    volumes:
      - ./docker_data/ftp:/home/vsftpd

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=5gasp
    volumes:
      - ./docker_data/data:/var/lib/postgresql/data
