# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   22-05-2022 10:25:05
# @Email:  rdireito@av.it.pt
# @Last Modified by:   Rafael Direito
# @Last Modified time: 26-05-2022 10:29:27
# @Description: Contains several constant variables needed in the workflow of the
# CI/CD Manager

from enum import Enum


# DEVELOPER DEFINED TESTS
DEVELOPER_DEFINED_TEST_TEMP_STORAGE_DIR = "warehouse/developer-defined-tests"
DEVELOPER_DEFINED_TEST_BASE_FTP_DIR = "developer-defined-tests"

# TESTING ARTIFACTS
TESTING_ARTIFACTS_FTP_ROOT_PATH = "/testing_artifacts"
DEFAULT_5GASP_TESTING_ARTIFACTS_FTP_ROOT_PATH = "/testing_artifacts/5gasp_default"
TESTING_ARTIFACTS_FTP_TEMP_STORAGE_DIR = "warehouse/testing-artifacts"
DEPLOYMENT_INFO_FNAME = "deployment-info.json"


# AUTH
SECRET_KEY = "99cb3e97787cf81a7f418c42b96a06f77ce25ddbb2f7f83a53cf3474896624f9"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
DEFAULT_ADMIN_CREDENTIALS = {
    "username": "admin",
    "password": "admin"
}
USER_ROLES = ["ADMIN", "USER"]

# CI/CD MANAGER 
CI_CD_MANAGER_URL = None

# TEST/TESTBED INFO
TEST_INFO = None
TEST_INFO_FILEPATH = None
TESTBED_INFO_FILEPATH = None

# Metrics Collection Info
METRICS_COLLECTION_INFO = None
METRICS_COLLECTION_INFO_FILEPATH = None

# FTP
FTP_RESULTS_USER = None
FTP_RESULTS_PASSWORD = None
FTP_RESULTS_URL = None

# FTP-LTR
FTP_LTR_USER = None
FTP_LTR_PASSWORD = None
FTP_LTR_URL = None

# Database
DB_NAME = None
DB_LOCATION = None
DB_USER = None
DB_PASSWORD = None

# Metrics Repository
MR_LOCATION = None
MR_DB = None

#NODS
NODS_USER=None
NODS_PASSWORD=None
NODS_HOST=None

#TRVD
TRVD_HOST=None

# Testbeds
TESTBEDS_INFO = None

# TaskIQ Broker
TASKIQ_BROKER_IP = "10.255.28.74"
TASKIQ_BROKER_PORT = 5672
TASKIQ_BROKER_USERNAME = "admin"
TASKIQ_BROKER_PASSWORD = "admin"
TASKIQ_REDIS_BACKEND_IP = "10.255.28.74"
TASKIQ_REDIS_BACKEND_PORT = 6379

# Possible Test Status
TEST_STATUS ={
    "submitted_on_manager": "SUBMITTED_TO_CI_CD_MANAGER",
    "testing_descriptor_obtained": "TESTING_DESCRIPTOR_OBTAINED",
    "testing_descriptor_rendered": "TESTING_DESCRIPTOR_RENDERED",
    "test_cases_validated_for_testbed": "TEST_CASES_VALIDATED_FOR_TESTBED",
    "developer_defined_tests_obtained": "DEVELOPER_DEFINED_TESTS_OBTAINED",
    "application_monitoring_configured": "APPLICATION_MONITORING_CONFIGURED",
    "application_logging_configured": "APPLICATION_LOGGING_CONFIGURED",
    "custom_ci_cd_agents_provisioned_started": "CUSTOM_CI_CD_AGENTS_PROVISIONED_STARTED",
    "custom_ci_cd_agents_provisioned_ended": "CUSTOM_CI_CD_AGENTS_PROVISIONED_ENDED",

    # check them
    "ci_cd_agent_provisioned": "PROVISIONED_CI_CD_AGENT",
    "ci_cd_agent_auth": "AUTHENTICATED_ON_CI_CD_AGENT",
    "created_comm_token": "CREATED_COMMUNICATION_TOKEN_ON_CI_CD_AGENT",
    "created_pipeline_script": "CREATED_PIPELINE_SCRIPT",
    "submitted_pipeline_script": "SUBMITTED_PIPELINE_SCRIPT",
    "ci_cd_agent_setup_environment": "ENVIRONMENT_SETUP_CI_CD_AGENT",
    "monitoring_started": "STARTED_MONITORING",
    "ci_cd_agent_obtained_tests": "OBTAINED_TESTS_ON_CI_CD_AGENT",
    "ci_cd_agent_performed_tests": "PERFORMED_TESTS_ON_CI_CD_AGENT",
    "ci_cd_agent_created_logs": "CREATED_LOGS_ON_CI_CD_AGENT",
    "monitoring_ended": "ENDED_MONITORING",
    "ci_cd_agent_published_test_results": "PUBLISHED_TEST_RESULTS",
    "ci_cd_agent_cleaned_test_environment": "CLEANED_TEST_ENVIRONMENT",
    "test_ended": "TEST_ENDED",
    "obtained_metrics_collection_files": "OBTAINED_METRICS_COLLECTION_FILES",
    "obtained_testing_artifacts_files": "OBTAINED_TESTING_ARTIFACTS_FILES"
}

TMF_SERVICE_TEST_DEPLOYMENT_INFO_KEY = "deployment_info"


class TestStatus(Enum):
    SUBMITTED_TO_CI_CD_MANAGER = "SUBMITTED_TO_CI_CD_MANAGER"
    TESTING_DESCRIPTOR_OBTAINED = "TESTING_DESCRIPTOR_OBTAINED"
    TESTING_DESCRIPTOR_RENDERED = "TESTING_DESCRIPTOR_RENDERED"
    TESTING_DESCRIPTOR_VALIDATED = "TESTING_DESCRIPTOR_VALIDATED"
    TESTING_TESTBED_VALIDATED = "TESTING_TESTBED_VALIDATED"
    TEST_CASES_VALIDATED_FOR_TESTBED = "TEST_CASES_VALIDATED_FOR_TESTBED"
    DEVELOPER_DEFINED_TESTS_OBTAINED = "DEVELOPER_DEFINED_TESTS_OBTAINED"
    APPLICATION_MONITORING_CONFIGURED = "APPLICATION_MONITORING_CONFIGURED"
    APPLICATION_LOGGING_CONFIGURED = "APPLICATION_LOGGING_CONFIGURED"
    CUSTOM_CI_CD_AGENTS_PROVISIONED_STARTED = "CUSTOM_CI_CD_AGENTS_PROVISIONED_STARTED"
    CUSTOM_CI_CD_AGENT_CONFIGURED = "CUSTOM_CI_CD_AGENT_CONFIGURED"
    CUSTOM_CI_CD_AGENTS_PROVISIONED_ENDED = "CUSTOM_CI_CD_AGENTS_PROVISIONED_ENDED"
    TESTING_PROCESS_STAGES_CONFIGURED = "TESTING_PROCESS_STAGES_CONFIGURED"
    TESTING_PROCESS_STARTED = "TESTING_PROCESS_STARTED"
    
    TESTING_PROCESS_ENDED = "TESTING_PROCESS_ENDED"
    PUBLISHED_TEST_RESULTS = "PUBLISHED_TEST_RESULTS"
    TEST_ENDED = "TEST_ENDED"
    #AUTHENTICATED_ON_CI_CD_AGENT = "AUTHENTICATED_ON_CI_CD_AGENT"
    #CREATED_COMMUNICATION_TOKEN_ON_CI_CD_AGENT = "CREATED_COMMUNICATION_TOKEN_ON_CI_CD_AGENT"

    #CREATED_PIPELINE_SCRIPT = "CREATED_PIPELINE_SCRIPT"
    #SUBMITTED_PIPELINE_SCRIPT = "SUBMITTED_PIPELINE_SCRIPT"
    #ENVIRONMENT_SETUP_CI_CD_AGENT = "ENVIRONMENT_SETUP_CI_CD_AGENT"
    #STARTED_MONITORING = "STARTED_MONITORING"
    #OBTAINED_TESTS_ON_CI_CD_AGENT = "OBTAINED_TESTS_ON_CI_CD_AGENT"
    #PERFORMED_TESTS_ON_CI_CD_AGENT = "PERFORMED_TESTS_ON_CI_CD_AGENT"
    #CREATED_LOGS_ON_CI_CD_AGENT = "CREATED_LOGS_ON_CI_CD_AGENT"
    #ENDED_MONITORING = "ENDED_MONITORING"
    #CLEANED_TEST_ENVIRONMENT = "CLEANED_TEST_ENVIRONMENT"
    
    #OBTAINED_METRICS_COLLECTION_FILES = "OBTAINED_METRICS_COLLECTION_FILES"
    #OBTAINED_TESTING_ARTIFACTS_FILES = "OBTAINED_TESTING_ARTIFACTS_FILES"

